
create table "public"."Customers" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "email" text
);


alter table "public"."Customers" enable row level security;


create table "public"."Items Ordered" (
    "id" bigint generated by default as identity not null,
    "product" text not null,
    "quantity" bigint,
    "price" double precision,
    "order_id" bigint
);


alter table "public"."Items Ordered" enable row level security;


create table "public"."Orders" (
    "id" bigint generated by default as identity not null,
    "date_ordered" date not null,
    "customer_id" bigint
);


alter table "public"."Orders" enable row level security;

CREATE UNIQUE INDEX "Customers_pkey" ON public."Customers" USING btree (id);

CREATE UNIQUE INDEX "Items Ordered_pkey" ON public."Items Ordered" USING btree (id);

CREATE UNIQUE INDEX "Orders_pkey" ON public."Orders" USING btree (id);

alter table "public"."Customers" add constraint "Customers_pkey" PRIMARY KEY using index "Customers_pkey";

alter table "public"."Items Ordered" add constraint "Items Ordered_pkey" PRIMARY KEY using index "Items Ordered_pkey";

alter table "public"."Orders" add constraint "Orders_pkey" PRIMARY KEY using index "Orders_pkey";

alter table "public"."Items Ordered" add constraint "Items Ordered_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public."Orders"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Items Ordered" validate constraint "Items Ordered_order_id_fkey";

alter table "public"."Orders" add constraint "Orders_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public."Customers"(id) not valid;

alter table "public"."Orders" validate constraint "Orders_customer_id_fkey";

grant delete on table "public"."Customers" to "anon";

grant insert on table "public"."Customers" to "anon";

grant references on table "public"."Customers" to "anon";

grant select on table "public"."Customers" to "anon";

grant trigger on table "public"."Customers" to "anon";

grant truncate on table "public"."Customers" to "anon";

grant update on table "public"."Customers" to "anon";

grant delete on table "public"."Customers" to "authenticated";

grant insert on table "public"."Customers" to "authenticated";

grant references on table "public"."Customers" to "authenticated";

grant select on table "public"."Customers" to "authenticated";

grant trigger on table "public"."Customers" to "authenticated";

grant truncate on table "public"."Customers" to "authenticated";

grant update on table "public"."Customers" to "authenticated";

grant delete on table "public"."Customers" to "service_role";

grant insert on table "public"."Customers" to "service_role";

grant references on table "public"."Customers" to "service_role";

grant select on table "public"."Customers" to "service_role";

grant trigger on table "public"."Customers" to "service_role";

grant truncate on table "public"."Customers" to "service_role";

grant update on table "public"."Customers" to "service_role";

grant delete on table "public"."Items Ordered" to "anon";

grant insert on table "public"."Items Ordered" to "anon";

grant references on table "public"."Items Ordered" to "anon";

grant select on table "public"."Items Ordered" to "anon";

grant trigger on table "public"."Items Ordered" to "anon";

grant truncate on table "public"."Items Ordered" to "anon";

grant update on table "public"."Items Ordered" to "anon";

grant delete on table "public"."Items Ordered" to "authenticated";

grant insert on table "public"."Items Ordered" to "authenticated";

grant references on table "public"."Items Ordered" to "authenticated";

grant select on table "public"."Items Ordered" to "authenticated";

grant trigger on table "public"."Items Ordered" to "authenticated";

grant truncate on table "public"."Items Ordered" to "authenticated";

grant update on table "public"."Items Ordered" to "authenticated";

grant delete on table "public"."Items Ordered" to "service_role";

grant insert on table "public"."Items Ordered" to "service_role";

grant references on table "public"."Items Ordered" to "service_role";

grant select on table "public"."Items Ordered" to "service_role";

grant trigger on table "public"."Items Ordered" to "service_role";

grant truncate on table "public"."Items Ordered" to "service_role";

grant update on table "public"."Items Ordered" to "service_role";

grant delete on table "public"."Orders" to "anon";

grant insert on table "public"."Orders" to "anon";

grant references on table "public"."Orders" to "anon";

grant select on table "public"."Orders" to "anon";

grant trigger on table "public"."Orders" to "anon";

grant truncate on table "public"."Orders" to "anon";

grant update on table "public"."Orders" to "anon";

grant delete on table "public"."Orders" to "authenticated";

grant insert on table "public"."Orders" to "authenticated";

grant references on table "public"."Orders" to "authenticated";

grant select on table "public"."Orders" to "authenticated";

grant trigger on table "public"."Orders" to "authenticated";

grant truncate on table "public"."Orders" to "authenticated";

grant update on table "public"."Orders" to "authenticated";

grant delete on table "public"."Orders" to "service_role";

grant insert on table "public"."Orders" to "service_role";

grant references on table "public"."Orders" to "service_role";

grant select on table "public"."Orders" to "service_role";

grant trigger on table "public"."Orders" to "service_role";

grant truncate on table "public"."Orders" to "service_role";

grant update on table "public"."Orders" to "service_role";


create policy "Enable read access for all users"
  on "public"."Customers"
  as permissive
  for select
  to public
using (true);



create policy "Enable read access for all users"
  on "public"."Items Ordered"
  as permissive
  for select
  to public
using (true);



create policy "Enable read access for all users"
  on "public"."Orders"
  as permissive
  for select
  to public
using (true);
