
  create table "public"."Inventory" (
    "id" bigint generated by default as identity not null,
    "product" text not null default ''::text,
    "price" double precision,
    "quantity" integer
      );


alter table "public"."Inventory" enable row level security;

CREATE UNIQUE INDEX "Inventory_pkey" ON public."Inventory" USING btree (id);

alter table "public"."Inventory" add constraint "Inventory_pkey" PRIMARY KEY using index "Inventory_pkey";

grant delete on table "public"."Inventory" to "anon";

grant insert on table "public"."Inventory" to "anon";

grant references on table "public"."Inventory" to "anon";

grant select on table "public"."Inventory" to "anon";

grant trigger on table "public"."Inventory" to "anon";

grant truncate on table "public"."Inventory" to "anon";

grant update on table "public"."Inventory" to "anon";

grant delete on table "public"."Inventory" to "authenticated";

grant insert on table "public"."Inventory" to "authenticated";

grant references on table "public"."Inventory" to "authenticated";

grant select on table "public"."Inventory" to "authenticated";

grant trigger on table "public"."Inventory" to "authenticated";

grant truncate on table "public"."Inventory" to "authenticated";

grant update on table "public"."Inventory" to "authenticated";

grant delete on table "public"."Inventory" to "service_role";

grant insert on table "public"."Inventory" to "service_role";

grant references on table "public"."Inventory" to "service_role";

grant select on table "public"."Inventory" to "service_role";

grant trigger on table "public"."Inventory" to "service_role";

grant truncate on table "public"."Inventory" to "service_role";

grant update on table "public"."Inventory" to "service_role";


  create policy "Enable read access for all users"
  on "public"."Inventory"
  as permissive
  for select
  to public
using (true);



